name: VCPKG Installation Validation

on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'

env:
  VCPKG_REPO: 'https://github.com/RealChuan/vcpkg.git'
  VCPKG_BRANCH: 'master'

jobs:
  validate-installation:
    name: Validate on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
      - name: Checkout action
        uses: actions/checkout@v4

      - name: Install Custom VCPKG
        uses: RealChuan/install-vcpkg@main
        with:
          repo: ${{ env.VCPKG_REPO }}
          branch: ${{ env.VCPKG_BRANCH }}

      - name: Verify branch and installation
        shell: bash
        run: |
          set -e
          
          # Determine vcpkg root directory based on OS
          if [ "$RUNNER_OS" = "Windows" ]; then
            vcpkg_root="/c/vcpkg"
          else
            vcpkg_root="/usr/local/share/vcpkg"
          fi
          
          echo "VCPKG Root: $vcpkg_root"
          
          # Verify repository branch
          if [ -d "$vcpkg_root" ]; then
            current_branch=$(git -C "$vcpkg_root" rev-parse --abbrev-ref HEAD)
            echo "Current branch: $current_branch"
            
            if [ "$current_branch" = "$VCPKG_BRANCH" ]; then
              echo "✓ Branch verification passed"
            else
              echo "✗ Branch mismatch: expected '$VCPKG_BRANCH', got '$current_branch'"
              exit 1
            fi
          else
            echo "✗ VCPKG directory not found"
            exit 1
          fi
          
          # Test vcpkg command
          echo "Testing vcpkg command..."
          vcpkg --version
          vcpkg list
          
          echo "✓ All verification tests passed"

      - name: Test basic vcpkg functionality
        shell: bash
        run: |
          # Test installing a simple package
          echo "Testing package installation..."
          vcpkg search fmt | head -5
          echo "✓ Basic functionality test passed"
          