name: Cross-Platform VCPKG Validation

on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README*'

env:
  VCPKG_REPO: 'https://github.com/RealChuan/vcpkg.git'
  VCPKG_BRANCH: 'master'

jobs:
  validate-vcpkg-installation:
    name: Validate VCPKG on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Install Custom VCPKG
        uses: RealChuan/install-vcpkg@main
        with:
          repo: ${{ env.VCPKG_REPO }}
          branch: ${{ env.VCPKG_BRANCH }}

      - name: Check branch on windows
        if: startsWith(runner.os, 'Windows')
        working-directory: C:\vcpkg
        shell: bash
        run: |
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          if [ "$current_branch" == "${{ env.VCPKG_BRANCH }}" ]; then
              echo "当前分支是${{ env.VCPKG_BRANCH }}"
          else
              echo "错误：当前分支不是${{ env.VCPKG_BRANCH }}"
              exit 1
          fi

      - name: Check branch on macos or ubuntu
        if: startsWith(runner.os, 'macOS') || startsWith(runner.os, 'Linux')
        working-directory: /usr/local/share/vcpkg
        shell: bash
        run: |
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          if [ "$current_branch" == "${{ env.VCPKG_BRANCH }}" ]; then
              echo "当前分支是${{ env.VCPKG_BRANCH }}"
          else
              echo "错误：当前分支不是${{ env.VCPKG_BRANCH }}"
              exit 1
          fi

      - name: Check vcpkg version
        shell: bash
        run: |
          vcpkg --version
