name: Test

on: 
  push:
    paths-ignore: 
        - '.gitignore'
        - 'LICENSE'
        - 'README*'
  pull_request:
    paths-ignore: 
        - '.gitignore'
        - 'LICENSE'
        - 'README*'

jobs:
  build:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        branch: [dev]

    steps:
      - name: Install Custom VCPKG
        uses: RealChuan/install-vcpkg@main
        with:
          repo: 'https://github.com/RealChuan/vcpkg.git'
          branch: '${{ matrix.branch }}'

      - name: Check branch on windows
        if: startsWith(runner.os, 'Windows')
        working-directory: C:\vcpkg
        shell: bash
        run: |
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          if [ "$current_branch" == "${{ matrix.branch }}" ]; then
              echo "当前分支是${{ matrix.branch }}"
          else
              echo "错误：当前分支不是${{ matrix.branch }}"
              exit 1
          fi

      - name: Check branch on macos or ubuntu
        if: startsWith(runner.os, 'macOS') || startsWith(runner.os, 'Linux')
        working-directory: /usr/local/share/vcpkg
        shell: bash
        run: |
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          if [ "$current_branch" == "${{ matrix.branch }}" ]; then
              echo "当前分支是${{ matrix.branch }}"
          else
              echo "错误：当前分支不是${{ matrix.branch }}"
              exit 1
          fi

      - name: Check vcpkg version
        shell: bash
        run: |
          vcpkg --version
